version: "3"
services:
    watcher:
        image: "watcherclient:latest"
        ports:
            - "4302:4302"
        depends_on:
            - api
        volumes:
            - "./volumes/watcher/config:/usr/share/nginx/html/assets/config"
    scoring:
        image: "scoringclient:latest"
        ports:
            - "4301:4301"
        depends_on:
            - api
        volumes:
            - "./volumes/scoring/config:/usr/share/nginx/html/assets/config"
    api:
        image: "game.server:latest"
        ports:
            - "4300:4300"
        depends_on:
            - db
        volumes:
            - "./volumes/api/config.json:/app/appsettings.Production.json"
    db:
        image: "microsoft/mssql-server-linux"
        container_name: trade-game-sql
        environment:
            SA_PASSWORD: "MSSQLServer_Linux"
            ACCEPT_EULA: "Y"
        ports:
            - "9004:1433"
        restart: always