version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        container_name: "stg-db"
        environment:
            SA_PASSWORD: "MSSQLServer_Linux"
            ACCEPT_EULA: "Y"
        ports:
            - "9001:1433"