version: "3"
services:
    watcher:
        image: "watcherclient:latest"
        ports:
            - "4301:4301"
        depends_on:
            - api
        #todo config - api address
    scoring:
        image: "scoringclient:latest"
        ports:
            - "4301:4301"
        depends_on:
            - api
        #todo config - api address
    api:
        image: "game.server:latest"
        ports:
            - "4300:4300"
        depends_on:
            - db
        #todo config - cors - db
    db:
        image: "microsoft/mssql-server-linux"
        container_name: scout-trade-game-sql
        environment:
            SA_PASSWORD: "MSSQLServer_Linux"
            ACCEPT_EULA: "Y"
        ports:
            - "9001:1433"
        restart: always